name: CityBuild
version: 1.0.0
api-version: 1.17
authors:
  - LPD
website: lcraft.de
main: de.lcraft.cb.main.Main
load: POSTWORLD

commands:
  tps:
    description: Show you the current TPS
  gm:
    description: Changes Gamemode
  gamemode:
    description: Changes Gamemode